.TH 91MENU 1 91menu\-VERSION
.SH NAME
91menu \- graphical mouse-driven menu
.SH SYNOPSIS
.B 91menu
.RB [ \-cglruv ]
.RB [ \-f
.IR file ]
.RB [ \-bd
.IR color ]
.RB [ \-bg
.IR color ]
.RB [ \-fg
.IR color ]
.RB [ \-nv
.IR color ]
.RB [ \-sl
.IR color ]
.RB [ \-ft
.IR font ]
.SH OPTIONS
.TP
.B \-c
Aligns the items to the center of the window.
.TP
.B \-g
Grabs every mouse buttons specified in config.h outside of the menu window.
.TP
.B \-l
Aligns the items to the left side of the window.
.TP
.B \-r
Aligns the items to the right side of the window.
.TP
.B \-u
Displays the 91menu usage message.
.TP
.B \-v
Displays the 91menu version.
.TP
.B \-f file
Specifies the file where 91menu should read the last selected item and write the selected one.
.TP
.B \-bd
Specifies the border color of the menu.
.TP
.B \-bg
Specifies the background color of the menu.
.TP
.B \-fg
Specifies the foreground color of the menu.
.TP
.B \-nv
Specifies the inverted text color of the menu.
.TP
.B \-sl
Specifies the selection color of the menu.
.SH DESCRIPTION
.B 91menu
is a graphical menu, meant to be a more versatile alternative to 9menu (to be more than a program launcher). The purpose of 91menu is to take a list of ordenated newline\-separated items from the sandard input, and display in the same order in a vertical menu, where items are selectable.

An item can be selected by pressing any mouse buttons over it (see config.h). When an item is selected, it is printed on the standard output, 91menu terminates, and the selected item is written as "last selected item" to a file specified with the -f option (or by default in the file specified in config.h). The next time 91menu will be executed, it will popup with the last selected item under the mouse cursor. The file specified with the -f option (or config.h) is used for reading and writing, and the readed item is overwriten by the selected one.
If some grabbed mouse buttons are pressed outside of the window, 91menu terminates, and nothing is printed on the standard output.

Unlike 9menu, 91menu only prints the selected item to standard output (instead of running a given command), this point makes 91menu way more flexible, and particulary usefull combined with a bunch of shell scripts.
.SH SEE ALSO
.IR 9menu(1)
